files:
  ignore: 'rocket-engine/styles/gui/overwrites/**'

# Rules Configuration
rules:
  # Mixins
  mixins-before-declarations: 0

  # Disallows
  no-color-literals: 0
  no-css-comments: 0
  no-vendor-prefixes: 0

  # Style
  indentation: 0
  hex-notation:
    - 1
    -
      style: lowercase
  nesting-depth:
    - 1
    -
      max-depth: 3
  property-sort-order:
    - 1
    -
      order: smacss # https://gist.github.com/chipcullen/b014d9d6885e1e785a31

  clean-import-paths:
    leading-underscore: true

  # Inner Spacing
  space-around-operator: 0

  # Final Items
  final-newline: 0